"""initial migration from current database

Revision ID: 7bd082391c6c
Revises: 
Create Date: 2025-05-12 22:35:21.290462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bd082391c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.alter_column('is_compulsory',
               existing_type=mysql.TINYINT(display_width=1),
               comment='该课程是否为该学生的必修',
               existing_comment='Whether the course is compulsory for this student',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('override_credit',
               existing_type=mysql.DECIMAL(precision=3, scale=1),
               type_=sa.Numeric(precision=4, scale=1),
               comment='覆盖课程学分（EQV或特殊情况）',
               existing_comment='覆盖课程学分（若为空则使用原课程学分）',
               existing_nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('OEN',
               existing_type=mysql.CHAR(length=9),
               type_=sa.String(length=9),
               existing_comment='OEN（9位数字，显示时格式化为XXX-XXX-XXX）',
               existing_nullable=False)
        batch_op.alter_column('birth_month',
               existing_type=mysql.ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'),
               comment='出生月份',
               existing_nullable=False)
        batch_op.alter_column('enrollment_month',
               existing_type=mysql.ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'),
               comment='入学月份',
               existing_nullable=False)
        batch_op.alter_column('expected_graduation_month',
               existing_type=mysql.ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'),
               comment='预计毕业月份',
               existing_nullable=False,
               existing_server_default=sa.text("'JUN'"))
        batch_op.alter_column('graduation_status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'GRADUATED', 'WITHDRAWN'),
               comment='毕业状态',
               existing_nullable=False,
               existing_server_default=sa.text("'IN_PROGRESS'"))
        batch_op.alter_column('grade',
               existing_type=mysql.ENUM('9', '10', '11', '12'),
               type_=sa.Enum('GRADE_9', 'GRADE_10', 'GRADE_11', 'GRADE_12', name='gradelevel'),
               existing_comment='学生当前年级',
               existing_nullable=False,
               existing_server_default=sa.text("'12'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='Username',
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='Password hash',
               existing_comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER'),
               comment='User role',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER'),
               comment=None,
               existing_comment='User role',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'"))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码哈希',
               existing_comment='Password hash',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名',
               existing_comment='Username',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_comment='User ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Enum('GRADE_9', 'GRADE_10', 'GRADE_11', 'GRADE_12', name='gradelevel'),
               type_=mysql.ENUM('9', '10', '11', '12'),
               existing_comment='学生当前年级',
               existing_nullable=False,
               existing_server_default=sa.text("'12'"))
        batch_op.alter_column('graduation_status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'GRADUATED', 'WITHDRAWN'),
               comment=None,
               existing_comment='毕业状态',
               existing_nullable=False,
               existing_server_default=sa.text("'IN_PROGRESS'"))
        batch_op.alter_column('expected_graduation_month',
               existing_type=mysql.ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'),
               comment=None,
               existing_comment='预计毕业月份',
               existing_nullable=False,
               existing_server_default=sa.text("'JUN'"))
        batch_op.alter_column('enrollment_month',
               existing_type=mysql.ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'),
               comment=None,
               existing_comment='入学月份',
               existing_nullable=False)
        batch_op.alter_column('birth_month',
               existing_type=mysql.ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'),
               comment=None,
               existing_comment='出生月份',
               existing_nullable=False)
        batch_op.alter_column('OEN',
               existing_type=sa.String(length=9),
               type_=mysql.CHAR(length=9),
               existing_comment='OEN（9位数字，显示时格式化为XXX-XXX-XXX）',
               existing_nullable=False)

    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.alter_column('override_credit',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=mysql.DECIMAL(precision=3, scale=1),
               comment='覆盖课程学分（若为空则使用原课程学分）',
               existing_comment='覆盖课程学分（EQV或特殊情况）',
               existing_nullable=True)
        batch_op.alter_column('is_compulsory',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether the course is compulsory for this student',
               existing_comment='该课程是否为该学生的必修',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
