LEARNING_COMMENTS = {
    "R": {
        "E": [
            "Consistently demonstrates outstanding responsibility.",
            "Shows exceptional ability in responsibility.",
            "Always exceeds expectations in responsibility.",
            "Maintains excellent performance in responsibility.",
            "Exhibits leadership and initiative in responsibility.",
            "Demonstrates maturity in handling responsibility responsibilities.",
            "Serves as a role model in responsibility.",
            "Proactively engages with tasks involving responsibility.",
            "Consistently reliable and thorough in responsibility.",
            "Shows great confidence and skill in responsibility tasks."
        ],
        "G": [
            "Generally performs well in responsibility.",
            "Meets expectations in most responsibility tasks.",
            "Usually organized and effective in responsibility.",
            "Maintains a steady effort in developing responsibility.",
            "Demonstrates a good understanding of responsibility responsibilities.",
            "Applies themselves well in responsibility with occasional support.",
            "Completes most tasks involving responsibility successfully.",
            "Maintains adequate performance in responsibility.",
            "Demonstrates responsibility and consistency in responsibility.",
            "Is generally prepared and on task in responsibility activities."
        ],
        "S": [
            "Requires support to improve responsibility.",
            "Struggles to meet expectations in responsibility.",
            "Needs reminders and guidance with responsibility tasks.",
            "Demonstrates inconsistent effort in responsibility.",
            "Often off-task or unprepared in responsibility settings.",
            "Has difficulty sustaining focus and meeting responsibility goals.",
            "Shows minimal progress in developing responsibility.",
            "Improvement is needed in areas related to responsibility.",
            "Frequently does not complete responsibility tasks independently.",
            "Needs ongoing support to build responsibility skills."
        ],
    },
    "O": {
        "E": [
            "Consistently demonstrates outstanding organization.",
            "Shows exceptional ability in organization.",
            "Always exceeds expectations in organization.",
            "Maintains excellent performance in organization.",
            "Exhibits leadership and initiative in organization.",
            "Demonstrates maturity in handling organization responsibilities.",
            "Serves as a role model in organization.",
            "Proactively engages with tasks involving organization.",
            "Consistently reliable and thorough in organization.",
            "Shows great confidence and skill in organization tasks."
        ],
        "G": [
            "Generally performs well in organization.",
            "Meets expectations in most organization tasks.",
            "Usually organized and effective in organization.",
            "Maintains a steady effort in developing organization.",
            "Demonstrates a good understanding of organization responsibilities.",
            "Applies themselves well in organization with occasional support.",
            "Completes most tasks involving organization successfully.",
            "Maintains adequate performance in organization.",
            "Demonstrates responsibility and consistency in organization.",
            "Is generally prepared and on task in organization activities."
        ],
        "S": [
            "Requires support to improve organization.",
            "Struggles to meet expectations in organization.",
            "Needs reminders and guidance with organization tasks.",
            "Demonstrates inconsistent effort in organization.",
            "Often off-task or unprepared in organization settings.",
            "Has difficulty sustaining focus and meeting organization goals.",
            "Shows minimal progress in developing organization.",
            "Improvement is needed in areas related to organization.",
            "Frequently does not complete organization tasks independently.",
            "Needs ongoing support to build organization skills."
        ],
    },
    "W": {
        "E": [
            "Consistently demonstrates outstanding independent work.",
            "Shows exceptional ability in independent work.",
            "Always exceeds expectations in independent work.",
            "Maintains excellent performance in independent work.",
            "Exhibits leadership and initiative in independent work.",
            "Demonstrates maturity in handling independent work responsibilities.",
            "Serves as a role model in independent work.",
            "Proactively engages with tasks involving independent work.",
            "Consistently reliable and thorough in independent work.",
            "Shows great confidence and skill in independent work tasks."
        ],
        "G": [
            "Generally performs well in independent work.",
            "Meets expectations in most independent work tasks.",
            "Usually organized and effective in independent work.",
            "Maintains a steady effort in developing independent work.",
            "Demonstrates a good understanding of independent work responsibilities.",
            "Applies themselves well in independent work with occasional support.",
            "Completes most tasks involving independent work successfully.",
            "Maintains adequate performance in independent work.",
            "Demonstrates responsibility and consistency in independent work.",
            "Is generally prepared and on task in independent work activities."
        ],
        "S": [
            "Requires support to improve independent work.",
            "Struggles to meet expectations in independent work.",
            "Needs reminders and guidance with independent work tasks.",
            "Demonstrates inconsistent effort in independent work.",
            "Often off-task or unprepared in independent work settings.",
            "Has difficulty sustaining focus and meeting independent work goals.",
            "Shows minimal progress in developing independent work.",
            "Improvement is needed in areas related to independent work.",
            "Frequently does not complete independent work tasks independently.",
            "Needs ongoing support to build independent work skills."
        ],
    },
    "C": {
        "E": [
            "Consistently demonstrates outstanding collaboration.",
            "Shows exceptional ability in collaboration.",
            "Always exceeds expectations in collaboration.",
            "Maintains excellent performance in collaboration.",
            "Exhibits leadership and initiative in collaboration.",
            "Demonstrates maturity in handling collaboration responsibilities.",
            "Serves as a role model in collaboration.",
            "Proactively engages with tasks involving collaboration.",
            "Consistently reliable and thorough in collaboration.",
            "Shows great confidence and skill in collaboration tasks."
        ],
        "G": [
            "Generally performs well in collaboration.",
            "Meets expectations in most collaboration tasks.",
            "Usually organized and effective in collaboration.",
            "Maintains a steady effort in developing collaboration.",
            "Demonstrates a good understanding of collaboration responsibilities.",
            "Applies themselves well in collaboration with occasional support.",
            "Completes most tasks involving collaboration successfully.",
            "Maintains adequate performance in collaboration.",
            "Demonstrates responsibility and consistency in collaboration.",
            "Is generally prepared and on task in collaboration activities."
        ],
        "S": [
            "Requires support to improve collaboration.",
            "Struggles to meet expectations in collaboration.",
            "Needs reminders and guidance with collaboration tasks.",
            "Demonstrates inconsistent effort in collaboration.",
            "Often off-task or unprepared in collaboration settings.",
            "Has difficulty sustaining focus and meeting collaboration goals.",
            "Shows minimal progress in developing collaboration.",
            "Improvement is needed in areas related to collaboration.",
            "Frequently does not complete collaboration tasks independently.",
            "Needs ongoing support to build collaboration skills."
        ],
    },
    "I": {
        "E": [
            "Consistently demonstrates outstanding initiative.",
            "Shows exceptional ability in initiative.",
            "Always exceeds expectations in initiative.",
            "Maintains excellent performance in initiative.",
            "Exhibits leadership and initiative in initiative.",
            "Demonstrates maturity in handling initiative responsibilities.",
            "Serves as a role model in initiative.",
            "Proactively engages with tasks involving initiative.",
            "Consistently reliable and thorough in initiative.",
            "Shows great confidence and skill in initiative tasks."
        ],
        "G": [
            "Generally performs well in initiative.",
            "Meets expectations in most initiative tasks.",
            "Usually organized and effective in initiative.",
            "Maintains a steady effort in developing initiative.",
            "Demonstrates a good understanding of initiative responsibilities.",
            "Applies themselves well in initiative with occasional support.",
            "Completes most tasks involving initiative successfully.",
            "Maintains adequate performance in initiative.",
            "Demonstrates responsibility and consistency in initiative.",
            "Is generally prepared and on task in initiative activities."
        ],
        "S": [
            "Requires support to improve initiative.",
            "Struggles to meet expectations in initiative.",
            "Needs reminders and guidance with initiative tasks.",
            "Demonstrates inconsistent effort in initiative.",
            "Often off-task or unprepared in initiative settings.",
            "Has difficulty sustaining focus and meeting initiative goals.",
            "Shows minimal progress in developing initiative.",
            "Improvement is needed in areas related to initiative.",
            "Frequently does not complete initiative tasks independently.",
            "Needs ongoing support to build initiative skills."
        ],
    },
    "S": {
        "E": [
            "Consistently demonstrates outstanding self-regulation.",
            "Shows exceptional ability in self-regulation.",
            "Always exceeds expectations in self-regulation.",
            "Maintains excellent performance in self-regulation.",
            "Exhibits leadership and initiative in self-regulation.",
            "Demonstrates maturity in handling self-regulation responsibilities.",
            "Serves as a role model in self-regulation.",
            "Proactively engages with tasks involving self-regulation.",
            "Consistently reliable and thorough in self-regulation.",
            "Shows great confidence and skill in self-regulation tasks."
        ],
        "G": [
            "Generally performs well in self-regulation.",
            "Meets expectations in most self-regulation tasks.",
            "Usually organized and effective in self-regulation.",
            "Maintains a steady effort in developing self-regulation.",
            "Demonstrates a good understanding of self-regulation responsibilities.",
            "Applies themselves well in self-regulation with occasional support.",
            "Completes most tasks involving self-regulation successfully.",
            "Maintains adequate performance in self-regulation.",
            "Demonstrates responsibility and consistency in self-regulation.",
            "Is generally prepared and on task in self-regulation activities."
        ],
        "S": [
            "Requires support to improve self-regulation.",
            "Struggles to meet expectations in self-regulation.",
            "Needs reminders and guidance with self-regulation tasks.",
            "Demonstrates inconsistent effort in self-regulation.",
            "Often off-task or unprepared in self-regulation settings.",
            "Has difficulty sustaining focus and meeting self-regulation goals.",
            "Shows minimal progress in developing self-regulation.",
            "Improvement is needed in areas related to self-regulation.",
            "Frequently does not complete self-regulation tasks independently.",
            "Needs ongoing support to build self-regulation skills."
        ],
    },
}
